// ============================================================
// Domain types — the single source of truth for all entities.
// These map 1:1 to database columns. Do not add UI-only state here.
// ============================================================

export type FlightStatus = 'Scheduled' | 'Delayed' | 'Departed' | 'Cancelled';
export type SeatClass = 'Economy' | 'Business' | 'First';
export type SeatStatus = 'Available' | 'Locked' | 'Booked';
export type BookingStatus = 'Confirmed' | 'Cancelled' | 'Rescheduled';

// Json type required by Supabase for JSONB columns and RPC JSONB args.
// This matches the type generated by `supabase gen types typescript`.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Flight {
  id: string;
  flight_number: string;
  origin: string;
  destination: string;
  departure_time: string;
  arrival_time: string;
  base_price: number;
  aircraft_type: string;
  status: FlightStatus;
  created_at: string;
}

export interface Seat {
  id: string;
  flight_id: string;
  seat_code: string;
  class: SeatClass;
  price_multiplier: number;
  // UI layer treats Locked + expired locked_until as Available.
  // Always compute effective status via the isEffectivelyAvailable util.
  status: SeatStatus;
  locked_until: string | null;
  locked_by: string | null;
  booking_id: string | null;
}

// Passenger detail stored in booking.passenger_details JSONB array.
// Sensitive fields (passport_number, date_of_birth) are stored only server-side;
// they must NOT be persisted in Zustand's localStorage slice.
export interface PassengerDetail {
  seat_code: string;
  title: 'Mr' | 'Ms' | 'Mrs' | 'Dr';
  first_name: string;
  last_name: string;
  // Sensitive: never persist to localStorage
  passport_number?: string;
  date_of_birth?: string;
}

export interface Booking {
  id: string;
  user_id: string | null;
  pnr: string;
  status: BookingStatus;
  total_price: number;
  passenger_details: PassengerDetail[];
  contact_email: string;
  created_at: string;
  updated_at: string;
}

// RPC response shapes
export interface LockSeatResult {
  success: boolean;
  error?: 'SEAT_NOT_FOUND' | 'SEAT_ALREADY_BOOKED' | 'SEAT_LOCKED' | 'SEAT_CONTENTION';
  locked_until?: string;
}

export interface ReserveSeatsResult {
  success: boolean;
  booking_id?: string;
  pnr?: string;
  error?: string;
}

export interface CancelBookingResult {
  success: boolean;
  error?: string;
}

export interface RescheduleBookingResult {
  success: boolean;
  error?: string;
}

// Supabase Database type map (used in createClient<Database>())
// NOTE: JSONB args in RPC functions MUST use `Json` type to satisfy
// the @supabase/supabase-js v2 internal typing constraints.
export type Database = {
  public: {
    Tables: {
      flights: {
        Row: Flight;
        Insert: Omit<Flight, 'id' | 'created_at'>;
        Update: Partial<Omit<Flight, 'id' | 'created_at'>>;
        Relationships: [];
      };
      seats: {
        Row: Seat;
        Insert: Omit<Seat, 'id'>;
        Update: Partial<Omit<Seat, 'id'>>;
        Relationships: [];
      };
      bookings: {
        Row: Booking;
        Insert: Omit<Booking, 'id' | 'pnr' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Booking, 'id' | 'pnr' | 'created_at'>>;
        Relationships: [];
      };
    };
    // Views is required by GenericSchema — must be present even if empty
    Views: Record<string, never>;
    Functions: {
      lock_seat: {
        Args: { p_flight_id: string; p_seat_code: string; p_session_id: string };
        Returns: Json;
      };
      release_seat_lock: {
        Args: { p_flight_id: string; p_seat_code: string; p_session_id: string };
        Returns: undefined;
      };
      reserve_seats: {
        Args: {
          p_flight_id:         string;
          p_seat_codes:        string[];
          p_session_id:        string;
          p_user_id:           string;
          p_contact_email:     string;
          p_total_price:       number;
          p_passenger_details: Json;
        };
        Returns: Json;
      };
      cancel_booking: {
        Args: { p_booking_id: string; p_user_id: string };
        Returns: Json;
      };
      reschedule_booking: {
        Args: {
          p_booking_id:     string;
          p_user_id:        string;
          p_new_flight_id:  string;
          p_new_seat_codes: string[];
          p_session_id:     string;
          p_price_delta:    number;
        };
        Returns: Json;
      };
    };
  };
};
